apiVersion: v1
kind: pod
metadate: 
  name: my-pod
  labels:
    env: dev
    version: v1
spec:
  containers:
    - name: my-container
      image: nginx:latest
      ports: 
      - containerPort: 80
    nodeSelector:
      az: b
        
 
