apiVersion: v1
kind: ReplicationController
metadata:
  name: my-repcon
spec:
  replicas: 3
  selector:
    env: dev
  template:
    metadata:
      labels: 
        env: dev
    spec: 
      containers:
      - name: my-pod
        image: nginx:latest
        ports:
        - containerPort: 80